[build]
  command = "npm run style-guide:build"
  publish = "build"
[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
[[headers]]
  for = "docs.*.(css|js)"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[redirects]]
  from = "/*"
  status = 200
  to = "/"
